export const SHIPMENT_STATUS = {
  PENDING: "PENDING",
  ASSIGNED: "ASSIGNED",
  CONFIRMED: "CONFIRMED",
  OUT_FOR_PICKUP: "OUT_FOR_PICKUP",
  PICKED_UP: "PICKED_UP",
  IN_TRANSIT: "IN_TRANSIT",
  OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
  DELIVERED: "DELIVERED",
  DELAYED: "DELAYED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
} as const;

export const SHIPMENT_TYPE = {
  STANDARD: "STANDARD",
  EXPRESS: "EXPRESS",
  SAME_DAY: "SAME_DAY",
} as const;

export const PAYMENT_STATUS = {
  PENDING: "PENDING",
  PAID: "PAID",
  FAILED: "FAILED",
} as const;
