export const COMPLAINT_SUBJECT = {
  PACKAGE_NOT_DELIVERED: "PACKAGE_NOT_DELIVERED",
  DAMAGED_PACKAGE: "DAMAGED_PACKAGE",
  WRONG_ITEM_DELIVERED: "WRONG_ITEM_DELIVERED",
  DELIVERY_DELAYED: "DELIVERY_DELAYED",
  AGENT_BEHAVIOUR: "AGENT_BEHAVIOUR",
  PARTIAL_DELIVERY: "PARTIAL_DELIVERY",
  LOST_PACKAGE: "LOST_PACKAGE",
  PAYMENT_ISSUE: "PAYMENT_ISSUE",
  OTHER: "OTHER",
} as const;

export const COMPLAINT_STATUS = {
  OPEN: "OPEN",
  IN_REVIEW: "IN_REVIEW",
  RESOLVED: "RESOLVED",
} as const;

export const COMPLAINT_STATUS_TRANSITIONS: Record<string, string> = {
  OPEN: "IN_REVIEW",
  IN_REVIEW: "RESOLVED",
};