export const NOTIFICATION_TYPE = {
  SHIPMENT_CREATED: "SHIPMENT_CREATED",
  AGENT_ASSIGNED: "AGENT_ASSIGNED",
  SHIPMENT_IN_TRANSIT: "SHIPMENT_IN_TRANSIT",
  SHIPMENT_DELAYED: "SHIPMENT_DELAYED",
  SHIPMENT_DELIVERED: "SHIPMENT_DELIVERED",
  SHIPMENT_COMPLETED: "SHIPMENT_COMPLETED",
  SHIPMENT_CANCELLED: "SHIPMENT_CANCELLED",
  PAYMENT_UPDATE: "PAYMENT_UPDATE",
  PAYMENT_REFUNDED: "PAYMENT_REFUNDED",
  GENERAL: "GENERAL",
  DELIVERY_OTP: "DELIVERY_OTP",
  AGENT_REASSIGNED: "AGENT_REASSIGNED",
} as const;
