export const NOTIFICATION_TYPE = {
  SHIPMENT_CREATED: "SHIPMENT_CREATED",
  AGENT_ASSIGNED: "AGENT_ASSIGNED",
  SHIPMENT_IN_TRANSIT: "SHIPMENT_IN_TRANSIT",
  SHIPMENT_DELAYED: "SHIPMENT_DELAYED",
  SHIPMENT_DELIVERED: "SHIPMENT_DELIVERED",
  SHIPMENT_COMPLETED: "SHIPMENT_COMPLETED",
  PAYMENT_UPDATE: "PAYMENT_UPDATE",
  GENERAL: "GENERAL",
  DELIVERY_OTP: "DELIVERY_OTP",
} as const;
